version: '3.1'

services:
  
  db:
    image: postgres:15
    container_name: weader-app-db
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - weader-app-db:/var/lib/postgresql/data/
      - ./initialDB/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - weader-app-network

  redis:
    image: redis:6
    container_name: weader-app-redis
    ports:
      - "6379:6379"
    env_file: .env
    volumes:
      - redis-data:/data
    networks:
      - weader-app-network

  backend:
    ports:
      - "3000:3000"
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    depends_on:
      - db
      - redis
    env_file: .env
    networks:
      - weader-app-network
  frontend:
    ports:
      - "4000:4000"
    build: 
      context: .
      dockerfile: frontend/Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    container_name: frontend
    depends_on:
      - backend
    env_file: .env
    networks:
      - weader-app-network
volumes:
  weader-app-db:
  redis-data:

networks:
  weader-app-network:
    driver: bridge